### ISSUE TITLE
syntax error importing the module

### ISSUE THREAD

**Issue by Eraldo** [doxiaodong/ng2-simplemde#1]
Loading the module works.
However as soon as I do:
```typescript
    SimplemdeModule.forRoot({
      provide: SIMPLEMDE_CONFIG,
      useValue: {
        placeholder: 'placeholder'
      }
    })
```
I get a syntax error crashing the loading process in the browser.
Tracing it back I get:
`export * from './src';` => `Uncaught SyntaxError: Unexpected token export`
in `node_modules/ng2-simplemde/index.js`

This could be related: https://github.com/ngx-translate/core/issues/291 (similar error message)

Ideas on how to fix it?

**Comment by doxiaodong** [comment]
@Eraldo ， thanks for the issue. you can try change `export * from './src'` to `export * from './src/index'`. if it works, I will change to it.

**Comment by Eraldo** [comment]
@doxiaodong Did not manage to get it to work that way yet.
I also tried reproducing it starting from scratch with: https://github.com/Urigo/angular2-meteor-base
=> To make sure it is not some local problem of mine.

I tried changing `export * from './src'` to `export * from './src/index'` in the `index.js` file: That did not change anything.

Have you tried to webpack config?
Can you take a look at the error using the base project linked above?

More ideas?

**Comment by doxiaodong** [comment]
@Eraldo , I'm trying to install meteor for long time.

**Comment by Eraldo** [comment]
@doxiaodong thanks for trying!
I did not understand what you mean by "I'm trying to install meteor for long time."

What I did:

Installing meteor:
`curl https://install.meteor.com/ | sh` (there is also a [windows installer](https://install.meteor.com/windows))

Installing the project:
```
git clone https://github.com/bsliran/angular2-meteor-base
cd angular2-meteor-base
meteor npm install
npm start
```

Can you tell me where you got stuck?

Update: Installing meteor does take quite long. I just uninstalled and installed it again to confirm. It did however finish successfully.

Besides -- I don't think meteor has anything to do with it. Any webpack project should be finde to check if webpack is having troubles with ng2-simplemde.
What do you think? Could it be the webpack config?

**Comment by doxiaodong** [comment]
@Eraldo , with the bad network inside China. I can't install meteor.  
I use `ng2-simplemde` in my project
https://github.com/doxiaodong/darlin-angular2/blob/master/src/app/app.module.ts#L21
https://github.com/doxiaodong/darlin-angular2/blob/master/src/app/share/index.ts#L21
https://github.com/doxiaodong/darlin-angular2/blob/master/src/app/article/declarations/comment/comment.template.html#L48

https://github.com/doxiaodong/darlin-angular2/blob/develop/config/webpack.common.js#L79

It can work both with `ts-loader` and `awesome-typescript-loader`

**Comment by doxiaodong** [comment]
You can have a try with the repo https://github.com/AngularClass/angular2-webpack-starter to see what is the problem.

**Comment by Eraldo** [comment]
@doxiaodong Thanks for sharing. I have checked your usages and updated mine to be the exact same ones (apart from fullscreen).

Here is my repo links:
https://github.com/Eraldo/colegend2/blob/simplemde/package.json#L38
https://github.com/Eraldo/colegend2/blob/simplemde/client/imports/app/app.module.ts#L29
https://github.com/Eraldo/colegend2/blob/simplemde/client/imports/app/app.module.ts#L101 

I still get the same error! :|

**Comment by doxiaodong** [comment]
I need to check meteor, I'm sorry for the network condition.

**Comment by Eraldo** [comment]
Yeah. I am sorry for asking you for help. I have spent hours trying different things but to be honest I have no clue what the problem is or where.
Thanks for the help @doxiaodong! :)

Maybe if you look at my project get an idea what is wrong.
For instance: I do not have even know which loader it is using. (I just followed the instructions)

**Comment by doxiaodong** [comment]
@Eraldo , I have found what the problem is. Just update the latest version. The meteor is use bundles, I have added the umd bundles support. Thank you for the issue. 😆 
And there is the change https://github.com/doxiaodong/ng2-simplemde/commit/9fdd1db4d113b3021bca26ded6a9df4c1bf22c6c

**Comment by Eraldo** [comment]
Awesome @doxiaodong ! :D
I'll try right now. *cheer*

**Comment by Eraldo** [comment]
I get:
```
Unable to resolve some modules:

  "!!./../../css-loader/index.js!./simplemde.min.css" in /Users/eraldo/Documents/colegend/alpha/colegend/node_modules/ng2-simplemde/bundles/index.umd.js (web.browser)
```

Yeah.. that is definitely one step closer. :)

**Comment by doxiaodong** [comment]
@Eraldo, after 1.0.0-rc.0. I drop the unreachable code. You can have a try.

**Comment by Eraldo** [comment]
Yeah! That's it. Working without any messages now. :)
*applaud*
Thank you @doxiaodong!

**Comment by doxiaodong** [comment]
move to close!
