### ISSUE TITLE
simplemde.min.css not getting injected in Angular 5.1

### ISSUE THREAD

**Issue by dzervas** [doxiaodong/ng2-simplemde#11]
I just import the module and use it inside a component. The CSS does not get injected (so the view is 
completely broken).
I import `SimplemdeModule.forRoot()` inside the module that has my component.

What info do you need to help me debug this?

EDIT: I added `"../node_modules/simplemde/dist/simplemde.min.css"` to my `angular-cli.json` and it works, but I don't like this approach.

**Comment by doxiaodong** [comment]
use webpack: style-loader!css-loader

**Comment by doxiaodong** [comment]
If you use angular-cli, you can add `style-loader!css-loader` as pug-loader in https://github.com/angular/angular-cli/issues/1886.

**Comment by sjml** [comment]
@doxiaodong Could you clarify what you mean by that comment? You link to a pretty long Issue thread, and it's not clear which part of it is meant to be relevant. Do we need to use pug-loader if we're using angular-cli, or are you saying to do something similar to what they do with pug-loader?

**Comment by doxiaodong** [comment]
yep, add style-loader!css-loader as just like pug-loader usage in the issue.

**Comment by vixson** [comment]
> yep, add style-loader!css-loader as just like pug-loader usage in the issue.

Please, how to add ` style-loader!css-loader ` to the webpack.

Because I don't think angular 5 have the *webpack.config.js* file anymore.

Please, it would be very helpful if an example is given on how to add the css loader. (_demo link_ or _Stackblitz_)

**Comment by doxiaodong** [comment]
you can use https://github.com/doxiaodong/ng2-simplemde#style . and add 'simplemde.min.css' to angular-cli config
I don't know how to implement with angular-cli with loader

**Comment by vixson** [comment]
> you can use https://github.com/doxiaodong/ng2-simplemde#style . and add 'simplemde.min.css' to angular-cli config
> I don't know how to implement with angular-cli with loader

Yeah, I think that's the best way. Thanks a lot @doxiaodong
