### ISSUE TITLE
Rendering for show page

### ISSUE THREAD

**Issue by ticklemycode** [doxiaodong/ng2-simplemde#13]
This is great for editing markdown and previewing it (awesome work btw) but I'm wondering if I need to use something else when rendering a show page or am I missing some utility to do that with your component?

Thanks

**Comment by doxiaodong** [comment]
It's hard to understand what you said, but you may get it from https://github.com/sparksuite/simplemde-markdown-editor

**Comment by ticklemycode** [comment]
Ok, I'll take a look over there but what I'm after is when I save my markdown to the database and then fetch it to just display the markdown as HTML. Like editing and showing a blog page.
