### ISSUE TITLE
how to implement

### ISSUE THREAD

**Issue by Stoffel-KT** [doxiaodong/ng2-simplemde#14]
I have been trying to implement this into my angular application for the last 4 days now...
Could you please help me out because I need this but I don't understand how to use it.

I've done the npm install and added it to my app.module.

I need to be able to create more or less the exact same editor screen as in the demo and will also need to extract the value of this area when a user has filled it in.

As far as I understand with this package I should easily be able to implement the full 'window' of this editor or am I completely wrong and should I construct this 'window' myself and this package will help me with a completely different part. 

(I only started coding about 8 months ago and oonly a week ago I heard about markdown for the first time since I needed to use it... some things that should be obvious often are not yet obvious to me, sorry ...)

kind regards

**Comment by doxiaodong** [comment]
Can you provide a demo repo on github? I don’t know what blocked you.

**Comment by Stoffel-KT** [comment]
Yesterday I changed something and suddenly I could see the toolbar but it's still acting very strange, it's not at all looking like the edit-window in the demo.

I created a new project where I implemented ng2-simplemde in the exact same way. It's looking exactly the same except for the toolbar (in my project the toolbar has got a blue color, I guess this has probably got something to do with my css where I give a-tags a custom color).

I created a github for this test project (it's the first time I've done this so I hope I've done it correct)
github --> Stoffel-KT/simplemde-test

**Comment by doxiaodong** [comment]
I don't see ng2-simplemde any place.  https://github.com/Stoffel-KT/simplemde-test/blob/master/package.json

**Comment by Stoffel-KT** [comment]
I think I had to commit all the changes I made after I did 'ng new ...'
I thought this wasn't necessary since I did not yet create anything on GitHub for this example.

Now it should be in there.

Thx for taking the time to have a look at what is holding me back by the way!

**Comment by doxiaodong** [comment]
I see, the ngModel is required, like `<simplemde [(ngModel)]="value"></simplemde>`. And the styles you can get it from https://github.com/doxiaodong/ng2-simplemde/issues/11.

And the demo code is in server dir at this repo.
