### ISSUE TITLE
how to change the options?

### ISSUE THREAD

**Issue by Stoffel-KT** [doxiaodong/ng2-simplemde#15]
Hello,

I've been trying to change the 'options', both in the app.module in .forRoot and in the simplemde selector with [options]="{...}" but I can't get it to work.
I'm trying to set autosave enabled to 'true'.

I've tried this in app module....

`SimplemdeModule.forRoot({
      provide: SIMPLEMDE_CONFIG,
      useValue: {
        autosave: {
          enabled: true,
        },
        placeholder: 'placeholder'
      }
    }),`

and tried many different ways of something similar to this in the the component where I'm implementing the markdown editor

`<simplemde formControlName="key"  [options]="{autosave.enable: true}"></simplemde>`

Thank you,
Kind regards!

**Comment by doxiaodong** [comment]
SimpleMDE: You must set a uniqueId to use the autosave feature

https://github.com/sparksuite/simplemde-markdown-editor#configuration

**Comment by Stoffel-KT** [comment]
Thx,

forgot about that apparantely.

I can do it for one editor but still trying to figure out how to set multiple unique id's in the configuration.

**Comment by doxiaodong** [comment]
~

**Comment by Stoffel-KT** [comment]
wow, thx for your quick reply!

That's exactly what I've been trying from the beginning (even without forgetting about the id ;) ), 
but when I do it like this the editor brakes and I get a standard textarea, so I guess I'm doing something else wrong somewhere or I've got something else installed that is braking it.

I'm getting an error: `Error: config is not an object`

**Comment by doxiaodong** [comment]
sorry
```html
<simplemde [(ngModel)]="x" [options]="{ autosave: { enabled: true, uniqueId: 1 } }"></simplemde>
<simplemde [(ngModel)]="y" [options]="{ autosave: { enabled: true, uniqueId: 2 } }"></simplemde>
```

**Comment by Stoffel-KT** [comment]
I had tried that as well :)
the editor looks normal again but the autosave is only working on the first one, not on the second editor in the same component. :)

**Comment by Stoffel-KT** [comment]
apparently for my application I don't need the autosave function from the editor but need to create a custom autosave function to save a full draft of the form a user is filling in :)
