### ISSUE TITLE
How to show line numbers

### ISSUE THREAD

**Issue by vixson** [doxiaodong/ng2-simplemde#20]
How to set options of the codemirror.
To show line numbers.
Example:
` lineNumbers: true,
 undoDepth: 1000
 ` etc

**Comment by doxiaodong** [comment]
https://github.com/sparksuite/simplemde-markdown-editor#configuration

**Comment by vixson** [comment]
> https://github.com/sparksuite/simplemde-markdown-editor#configuration

I have checked the configuration.
And it requires the use of codemirror in the simplemde.

So is there a way to bind to codemirror options on the component.

Example:
` <simplemde [codemirror]="extraOptions"></simplemde> `

**Comment by doxiaodong** [comment]
the simplemde doesn't have the config

**Comment by vixson** [comment]
> the simplemde doesn't have the config

Yes. But it can be done by calling the ` .setOption('lineNumbers', true)` from codemirror in the simplemde  construct.

i.e:
```Javascript
var mde = new SimpleMDE();
mde.codemirror.setOption('lineNumbers', true);
mde.codemirror.setOption('undoDepth', 10); // can be 0 - any number
``` 

So, I was hoping that the ng-simplemde would have an easy databind of the codemirror.
Like this: `<simplemde [codemirror]="extraOptions"></simplemde>`.

Thank You! @doxiaodong

**Comment by vixson** [comment]
I got a way around it.
**HTML templete**
```HTML
<simplemde #editor></simplemde>
```
**Component**
```TS
extraOptions = {
    lineNumbers: true,
    ...more
};
...
@ViewChild('editor') mEditor: ElementRef;
...
ngOnInit() {
   this.setCodeMirrorOptions(extraOptions);
}

private setCodeMirrorOptions(opts) {
    let mSimplemde = this.mEditor.simplemde; // An instance of the SimpleMDE
    for (const [k, v] of Object.entries(opts)) {
	mSimplemde.codemirror.setOption(k, v);
    };
}
````
In this case use HTMLElement Reference on the `<simplemde>` tag.
Then get the instance of the SimpleMDE from it.
😊

**Comment by doxiaodong** [comment]
see 2.1.0

**Comment by vixson** [comment]
> see 2.1.0

Thanks a lot for the integration. 🥂

**Comment by doxiaodong** [comment]
https://github.com/doxiaodong/ng2-simplemde/releases/tag/v2.1.0
