### ISSUE TITLE
Added non-passive event listener to a scroll-blocking <some> event

### ISSUE THREAD

**Issue by tmeghe** [doxiaodong/ng2-simplemde#21]
Hello,

I'm using this module with Angular 6 and it works great (thanks for the implementation). However, I have the following warning in console log :

`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>`

Is there something I did wrongly ?

Thanks,

**Comment by doxiaodong** [comment]
Do you have event listener? try to add `{passive:true}`. 
```
document.addEventListener('touchstart', handler, {passive: true});.
```
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by tmeghe** [comment]
I resolved it using a Node package to enable passive by default when possible.
