### ISSUE TITLE
Warning: Entry point 'ng2-simplemde' contains deep imports

### ISSUE THREAD

**Issue by suhailkc** [doxiaodong/ng2-simplemde#24]
Waring when `ng serve`

`Warning: Entry point 'ng2-simplemde' contains deep imports into '/Users/xxx/node_modules/simplemde/dist/simplemde.min.css'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

Angular CLI: 9.1.3
Node: 12.14.0
OS: macOS

**Comment by vixson** [comment]
There is no big issue here. Its not gonna affect anything.
Try importing the simplemde css from your main css
___
_**.main.css_
```css
import "~simplemde/dist/simplemde.min.css"
```
