### ISSUE TITLE
Error:  SimplemdeModule.forRoot returns a ModuleWithProviders type without a generic type argument.

### ISSUE THREAD

**Issue by zhangdongdongzdd** [doxiaodong/ng2-simplemde#25]
SimplemdeModule.forRoot returns a ModuleWithProviders type **without a generic type argumen**t. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

**Comment by vixson** [comment]
Please how did you declare your NgModule?
Snip & Paste it here>>>
