### ISSUE TITLE
simplemde.min.css not found

### ISSUE THREAD

**Issue by MaxGoh** [doxiaodong/ng2-simplemde#4]
Hi. I have been using your package for awhile and would love to say Thank you. 

I recently suddenly encountered into this issue right now. 

```
GET http://localhost:4200/node_modules/simplemde/dist/simplemde.min.css 404 (Not Found)

Unhandled Promise rejection: Failed to load ../node_modules/simplemde/dist/simplemde.min.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ../node_modules/simplemde/dist/simplemde.min.css undefined
```
I thought I broke something at the start, but I created a new angular project and did the installation, and still got the same error.

Any fixes?

**Comment by ZinLiao** [comment]
i have the same problem

**Comment by doxiaodong** [comment]
A workaround way is locking the version to 1.1.0 until next version release.  Sorry!

**Comment by MaxGoh** [comment]
No worries about it @doxiaodong , I've been doing that for sometimes now, just let us know when if you are going to update it. I'm closing this issue now. :)

**Comment by doxiaodong** [comment]
Keep this open until next update.

**Comment by Palad1NPT** [comment]
when will this be fixed? thank you

**Comment by doxiaodong** [comment]
I will revert to 1.1.0 this weekend.

**Comment by doxiaodong** [comment]
release 1.3.0 to revert
