### ISSUE TITLE
Calling function 'SimplemdeModule', function calls are not supported

### ISSUE THREAD

**Issue by richiethom** [doxiaodong/ng2-simplemde#5]
I'm sorry if this isn't a problem with ng2-simplemde, feel free to let me know if this is the case.

I am trying to use ng2-simplemde in a JHipster project.

I have added the dependency to ng2-simplemde version 1.3.0 (via `yarn add --exact ng2-simplemde@1.3.0`), and have added the following line to the vendor.ts file:

`import 'ng2-simplemde/bundles/ng2-simplemde.umd.min.js';`

I have then modified `app.module.ts` with the following lines:

```
import { SimplemdeModule, SIMPLEMDE_CONFIG } from 'ng2-simplemde';

@NgModule({
    imports: [
        ....
        SimplemdeModule.forRoot({
            provide: SIMPLEMDE_CONFIG
          })
    ]
})
```
I then run `yarn run webpack:build`, which in turn runs `ngc -p tsconfig-aot.json`, and there I get the following error:

```
Error encountered resolving symbol values statically. Calling function 'SimplemdeModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol myprojectAppModule in C:/Users/richi/Documents/projects/myproject/src/main/webapp/app/app.module.ts, resolving symbol myprojectAppModule in C:/Users/richi/Documents/projects/myproject/src/main/webapp/app/app.module.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What am I doing wrong?

**Comment by lakhansamani** [comment]
Facing the same issue

**Comment by doxiaodong** [comment]
Sorry for late.
Is this repo https://github.com/jhipster/ng-jhipster?
It doesn't need import `'ng2-simplemde/bundles/ng2-simplemde.umd.min.js'`.

May you provide a simple repo for me?

**Comment by richiethom** [comment]
Thanks for getting back to me.

Yes, that's the correct repository - the main website is [here](http://www.jhipster.tech/).

I'll make a simple repo for you as soon as possible.

**Comment by richiethom** [comment]
I have pushed [a repository](https://github.com/richiethom/simplemdedemo) - hopefully it contains everything you need. The readme.md describes the steps to reproduce.

Please don't hesitate to get back to me if you have any questions or if you need any modifications.

**Comment by doxiaodong** [comment]
I will try it this night.

**Comment by doxiaodong** [comment]
@richiethom , This is caused by `angular-cli`.
Maybe you can find what you want in `https://github.com/angular/angular-cli/issues/4647`.
Sorry that I don't find a way to fix this.

**Comment by richiethom** [comment]
Thanks for taking a look so soon after I posted the repository. It looks like this therefore isn't linked to ng2-simplemde - thanks again for your help, and for the work you've done on ng2-simplemde!
