### ISSUE TITLE
Cannot find name '$options1'

### ISSUE THREAD

**Issue by orochiZhang** [doxiaodong/ng2-simplemde#7]
I use ng2-simplemde in angular4 cli.there is a error say " Cannot find name '$options1' "
![image](https://user-images.githubusercontent.com/16440767/30480354-f393eb3a-99de-11e7-9714-8244af58a8d3.png)

**Comment by doxiaodong** [comment]
Hi, you can get it at https://github.com/doxiaodong/ng2-simplemde/blob/master/server/app/app.module.ts#L17

**Comment by orochiZhang** [comment]
thanks
