### ISSUE TITLE
Importing Module in Angular 4.4.3 results in an error

### ISSUE THREAD

**Issue by klemmchr** [doxiaodong/ng2-simplemde#8]
In Angular 4.4.3 importing the `SimplemdeModule` results in a compiler error.

I tried the import with this two ways
```typescript
SimplemdeModule.forRoot(),

SimplemdeModule.forRoot({
    provide: SIMPLEMDE_CONFIG,
    useValue: {}
})
```

which results in this error for both variants
```
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'SimplemdeModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol <module> in <pathToModule> [...]
```

AFAIK this is because of missing compiler flags. Seems to be an issue with AOT.

**Comment by doxiaodong** [comment]
Sorry it loosed in last several versions. Fixed in https://github.com/doxiaodong/ng2-simplemde/commit/4b1a0b260767474228d6daf40a154d72cdb75d2c and release in v1.3.3

**Comment by klemmchr** [comment]
Thanks for the quick fix.
