### ISSUE TITLE
ng2-simplemde not working with Angular 5

### ISSUE THREAD

**Issue by carstenbaumhoegger** [doxiaodong/ng2-simplemde#9]
Because of the use of `OpaqueToken` which was deprecated in Angular 4 and removed in Angular 5, this module doesn't work with Angular 5.

I created [this](https://github.com/doxiaodong/ng2-simplemde/pull/10) Pull-Request to fix it.

**Comment by doxiaodong** [comment]
thanks

**Comment by doxiaodong** [comment]
release 2.0.0 https://github.com/doxiaodong/ng2-simplemde/releases/tag/v2.0.0

**Comment by carstenbaumhoegger** [comment]
thanks for the fast merge and release! :)
